version: "3"

services:
  front:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile.dev
    ports:
      - 3000:3000
    volumes:
      - /project/frontend/node_modules
      - ./frontend:/project/frontend
    command: ['npm', 'run', 'start']
    stdin_open: true
