FROM node:16.14.2

# RUN mkdir -p project/frontend/node_modules/.cache

# RUN chmod -R node:node /project/frontend/node_modules

# RUN chown -R node:node /project/frontend/node_modules

# USER node

WORKDIR /project/frontend

COPY frontend/package.json ./
COPY frontend/package-lock.json ./

RUN npm install

# COPY ./frontend /project/frontend