# Generated by Django 4.0.4 on 2022-05-28 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commnent', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('depth', models.IntegerField()),
                ('has_repo', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('content_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('ananymous', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('content_class', models.CharField(choices=[('Free', 'Free'), ('Info', 'Info')], default='Free', max_length=30)),
                ('title', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Detach',
            fields=[
                ('detach_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('image_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('path', models.ImageField(upload_to='media/file')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('image_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('path', models.ImageField(upload_to='images/detach/')),
            ],
        ),
        migrations.CreateModel(
            name='React',
            fields=[
                ('react_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('react_type', models.CharField(choices=[('GOOD', 'GOOD'), ('BAD', 'BAD')], default='GOOD', max_length=30)),
                ('comment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boards.comment')),
                ('content_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boards.content')),
            ],
        ),
    ]
