# Generated by Django 4.0.4 on 2022-05-28 10:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('boards', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='react',
            name='user_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='image',
            name='comment_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='boards.comment'),
        ),
        migrations.AddField(
            model_name='image',
            name='content_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='boards.content'),
        ),
        migrations.AddField(
            model_name='image',
            name='detach_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='boards.detach'),
        ),
        migrations.AddField(
            model_name='file',
            name='detach_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='boards.detach'),
        ),
        migrations.AddField(
            model_name='detach',
            name='comment_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boards.comment'),
        ),
        migrations.AddField(
            model_name='detach',
            name='content_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boards.content'),
        ),
        migrations.AddField(
            model_name='content',
            name='user_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boards.comment'),
        ),
        migrations.AddField(
            model_name='comment',
            name='content_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boards.content'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
