# Generated by Django 4.0.4 on 2022-05-29 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='user_name',
        ),
    ]
